email:
  smtp_server: smtp.gmail.com
  port: 587
  username: your_email@gmail.com
  password: your_app_password
  sender: your_email@gmail.com
  recipient: recipient@email.com

telegram:
  token: your_telegram_bot_token
  chat_id: your_chat_id

reddit:
  client_id: your_reddit_client_id
  client_secret: your_reddit_client_secret
  user_agent: your_user_agent

twitter:
  bearer_token: your_twitter_bearer_token
  consumer_key: your_twitter_api_key
  consumer_secret: your_twitter_api_secret
  access_token: your_twitter_access_token
  access_token_secret: your_twitter_access_token_secret 

alpaca:
  api_key: your_alpaca_api_key
  api_secret: your_alpaca_api_secret
  base_url: https://paper-api.alpaca.markets  # Use paper trading for testing

automated_trading:
  enabled: false  # Set to true to enable automated trading
  max_position_size: 0.1  # Maximum position size as fraction of portfolio
  stop_loss_pct: 0.02  # Stop loss percentage 